// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar/>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default Layout;
